<select {{ $attributes->merge(['class' => 'form-select form-select-md']) }}>
    <option value="">Select</option>
    <option value="Wife">Wife</option>
    <option value="Husband">Husband</option>
    <option value="Daughter">Daughter</option>
    <option value="Son">Son</option>
    <option value="Mother">Mother</option>
    <option value="Father">Father</option>
    <option value="Sister">Sister</option>
    <option value="Brother">Brother</option>
    <option value="Auntie">Auntie</option>
    <option value="Uncle">Uncle</option>
    <option value="Niece">Niece</option>
    <option value="Nephew">Nephew</option>
    <option value="Cousin">Cousin</option>
    <option value="Other">Other</option>
    <option value="Mother-in-law">Mother-in-law</option>
    <option value="Father-in-law">Father-in-law</option>
    <option value="Daughter-in-law">Daughter-in-law</option>
    <option value="Son-in-law">Son-in-law</option>
    <option value="Sister-in-law">Sister-in-law</option>
    <option value="Brother-in-law">Brother-in-law</option>
</select>
