<select {{ $attributes->merge(['class' => 'form-select form-select-md']) }}>
    <option value="">Select</option>
    <option value="Ampoule(s)">Ampoule(s)</option>
    <option value="Bottle(s)">Bottle(s)</option>
    <option value="Box(es)">Box(es)</option>
    <option value="Capsule(s)">Capsule(s)</option>
    <option value="Cards(s)">Card(s)</option>
    <option value="Copy(ies)">Copy(ies)</option>
    <option value="Infusion(s)">Infusion(s)</option>
    <option value="IU">IU</option>
    <option value="Ml(s)">Ml(s)</option>
    <option value="Operation(s)">Operation(s)</option>
    <option value="Packs">Pack(s)</option>
    <option value="Per day">Per day</option>
    <option value="Pair(s)">Pair(s)</option>
    <option value="Piece(s)">Piece(s)</option>
    <option value="Procedure(s)">Procedure(s)</option>
    <option value="Roll(s)">Roll(s)</option>
    <option value="Sachet(s)">Sachet(s)</option>
    <option value="Scan(s)">Scan(s)</option>
    <option value="Service(s)">Service(s)</option>
    <option value="Session(s)">Session(s)</option>
    <option value="Shot(s)">Shot(s)</option>
    <option value="Spoon(s)">Spoon(s)</option>
    <option value="Suppositories">Suppositories</option>
    <option value="Tab(s)">Tab(s)</option>
    <option value="Test(s)">Test(s)</option>
    <option value="Tube(s)">Tube(s)</option>
    <option value="Vial(s)">Vial(s)</option>
</select>