const consultationDetails = {
    "data": [
        {
            "id": 120,
            "date": "10-Jul-2023",
            "name": "Naomi",
            "bloodPressure": "120/80mmgh",
            "temperature": "37.6",
            "sugarLevel": "5.0mmlo",
            "respiratoryRate": "30",
            "pulseRate": 95,
            "height": "1.6m",
            "weight": "102kg",
            "activeUser": "Admin",
            "selectedDiagnosis": "Malingering"
        },
        {
            "id": 119,
            "date": "08-Jul-2023",
            "name": "Helen",
            "bloodPressure": "145/90mmgh",
            "temperature": "36.5",
            "sugarLevel": "4.5mmlo",
            "respiratoryRate": "25",
            "pulseRate": 82,
            "height": "1.42m",
            "weight": "88kg",
            "activeUser": "Admin",
            "selectedDiagnosis": "Gastro-enterities",
            "complain": "Headache and weakness in the knees. But also, patient wants to talk for long. He wants to go on and on and on. I want to continue writing all these things till the line overflows",
            "examinationFindings": "Server yellowness in both eyes",
            "notes": "patient not improved after 24hrs of rocephine. I will continue",
            "plan": "change to meropenim for the next 24hrs, and if no improvement, refer.",
            "status": "Out-Patient",
            "ward": "Private Ward"
        },
        {
            "id": 118,
            "date": "08-Jul-2023",
            "name": "Tabitha",
            "bloodPressure": "90/60mmgh",
            "temperature": "39.0",
            "sugarLevel": "7.4mmlo",
            "respiratoryRate": "42",
            "pulseRate": 67,
            "height": "1.2m",
            "weight": "56kg",
            "activeUser": "Admin",
            "selectedDiagnosis": "Acid Flux"
        },
        {
            "id": 117,
            "date": "08-Jul-2023",
            "name": "Adorable Event",
            "bloodPressure": "160/110mmgh",
            "temperature": "37.2",
            "sugarLevel": "5.0mmlo",
            "respiratoryRate": "32",
            "pulseRate": 80,
            "height": "1.45m",
            "weight": "96kg",
            "activeUser": "Admin",
            "selectedDiagnosis": "Acute Spundolosis"
        },
        // {
        //     "id": 116,
        //     "date": "08-Jul-2023",
        //     "name": "Mrs Grace",
        //     "bloodPressure": "110/70mmgh",
        //     "temperature": "38.5",
        //     "sugarLevel": "3.8mmlo",
        //     "respiratoryRate": "30",
        //     "pulseRate": 75,
        //     "height": "1.32m",
        //     "weight": "77kg",
        //     "activeUser": "Admin",
        //     "selectedDiagnosis": ""
        // },
        // {
        //     "id": 115,
        //     "date": "08-Jul-2023",
        //     "name": "CONESAM NG",
        //     "bloodPressure": "120/90mmgh",
        //     "temperature": "38.1",
        //     "sugarLevel": "5.6mmlo",
        //     "respiratoryRate": "27",
        //     "pulseRate": 88,
        //     "height": "1.5m",
        //     "weight": "103",
        //     "activeUser": "Admin"
        // },
        // {
        //     "id": 114,
        //     "date": "08-Jul-2023",
        //     "name": "ORENDA",
        //     "bloodPressure": "140/100mmgh",
        //     "temperature": "37.5",
        //     "sugarLevel": "9.0mmlo",
        //     "respiratoryRate": "29",
        //     "pulseRate": 90,
        //     "height": "1.3m",
        //     "weight": "65kg",
        //     "activeUser": "Admin"
        // },
        // {
        //     "id": 113,
        //     "date": "08-Jul-2023",
        //     "name": "Naomi",
        //     "bloodPressure": "125/70mmgh",
        //     "temperature": "39.2",
        //     "sugarLevel": "8.4mmlo",
        //     "respiratoryRate": "15Studio pictures",
        //     "pulseRate": 74,
        //     "height": "1.2m",
        //     "weight": "70kg",
        //     "activeUser": "Admin"
        // },
        // {
        //     "id": 112,
        //     "date": "07-Jul-2023",
        //     "name": "Casandra",
        //     "bloodPressure": "130/90mmgh",
        //     "temperature": "37.8",
        //     "sugarLevel": "3.4mmlo",
        //     "respiratoryRate": "32",
        //     "pulseRate": 80,
        //     "height": "1.35m",
        //     "weight": "67kg",
        //     "activeUser": "Admin"
        // },
        // {
        //     "id": 111,
        //     "date": "07-Jul-2023",
        //     "name": "Daniel",
        //     "bloodPressure": "150/100mmgh",
        //     "temperature": "36.9",
        //     "sugarLevel": "9.6mmlo",
        //     "respiratoryRate": "28",
        //     "pulseRate": 100,
        //     "height": "1.4m",
        //     "weight": "89kg",
        //     "activeUser": "Admin"
        // }
    ],
}

export {consultationDetails}