<div class="container">
    <div class="modal fade " id="{{ $id }}" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fs-4 text-primary">{{ $title }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body billSummaryBody overflow-auto">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <header class="d-flex flex-wrap justify-content-between align-items-top mb-4">
                        <div class="text-left p-0">
                            <h4 class="">Sandra Hospital Makurdi</h4>
                            <p>{{ date('g:ia F j, Y') }}</p>
                        </div>
                    </header>

                    <div class="text-center">
                        <label for="basic-url" class="form-label fs-4 mb-3 fw-bold mainLable">Bill <span class="changeBill">Summary</span></label>
                    </div>
                    <div class="row mb-2">
                        <x-form-span class="fw-bold">Patient's Information</x-form-span>
                        <x-form-div class="col-xl-12">
                            <span class="patient"></span>
                        </x-form-div>
                    </div>
                    <div class="mb-2 form-control overflow-auto">
                        <X-form-div class="mt-3">
                            <table id="billTable" class="table table-sm billTable">
                                <thead>
                                    <tr>
                                        <th>Service(s)</th>
                                        <th>Type(s)</th>
                                        <th>Quantity</th>
                                        <th>Total Bill</th>
                                        <th>Total Paid</th>
                                        <th>Balance</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                                <tfoot>
                                    <tr class="">
                                        <td></td>
                                        <td></td>
                                        <td class="fw-semibold">Discount</td>
                                        <td></td>
                                        <td> - </td>
                                        <td> - </td>
                                    </tr>
                                    <tr class="">
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td class="fw-bold"></td>
                                        <td class="fw-bold"></td>
                                        <td class="fw-bold"></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </X-form-div>
                    </div>
                    <div class="row mt-3">
                        <x-form-span class="fw-bold">Generated By</x-form-span>
                        <x-form-div class="col-xl-12">
                            <span class="billingStaff"></span>
                        </x-form-div>
                    </div>
                </div>
                <div class="modal-footer px-5">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                        <i class="bi bi-x-circle me-1"></i>
                        Close
                    </button>
                    <button type="button" id="downloadBillSummaryBtn" class="btn btn-primary">
                        <i class="bi bi-download"></i>
                        Download
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
