<div class="container">
    <div class="modal fade " id="{{ $id }}" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-small">
            <div class="modal-content px-1" @style(['width: 300px' => $isPos, 'font-size: 12px' => $isPos])>
                <div class="modal-header">
                    <h5 class="modal-title fs-4 text-primary">{{ $title }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body posBillSummaryBody">
                    <header class="d-flex flex-wrap justify-content-between align-items-top mb-0">
                        <div class="text-left p-0">
                            <p class="fw-bold {{ $isPos ? 'small' : ''}}">Ufor Hospital Ughelli</p>
                            <p class="small">{{ date('g:ia F j, Y') }}</p>
                        </div>
                    </header>

                    <div class="text-center">
                        <label for="basic-url" class="form-label fw-bold small fw-bold mainLable">Bill <span class="changePosBill">Summary</span></label>
                    </div>
                    <div class="row mb-0">
                        <x-form-span class="fw-bold small">Patient's Information</x-form-span>
                        <x-form-div class="col-xl-12">
                            <span class="patient small"></span>
                        </x-form-div>
                    </div>
                    <div class="mb-2">
                        <X-form-div class="mt-0">
                            <table id="posBillTable" class="table table-sm billTable">
                                <thead>
                                    <tr>
                                        <th>Services</th>
                                        <th>Qty</th>
                                        <th>Total Bill</th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                                <tfoot>
                                    <tr class="">
                                        <td></td>
                                        <td class="fw-semibold">Total</td>
                                        <td></td>
                                    </tr>
                                    <tr class="{{ $isWalkIn ? 'd-none' : '' }}">
                                        <td></td>
                                        <td class="fw-semibold">Discount</td>
                                        <td></td>
                                    </tr>
                                    <tr class="">
                                        <td></td>
                                        <td class="fw-semibold">Total Paid</td>
                                        <td class="fw-bold"></td>
                                    </tr>
                                    <tr class="">
                                        <td></td>
                                        <td class="fw-semibold">Balance</td>
                                        <td class="fw-bold"></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </X-form-div>
                    </div>
                    <div class="row mt-0">
                        <x-form-span class="small">Generated By</x-form-span>
                        <x-form-div class="col-xl-12">
                            <span class="billingStaff small"></span>
                        </x-form-div>
                    </div>
                </div>
                <div class="modal-footer px-5">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                        <i class="bi bi-x-circle me-1"></i>
                        Close
                    </button>
                    <button type="button" id="downloadPosBillSummaryBtn" class="btn btn-primary">
                        <i class="bi bi-download"></i>
                        Download
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
